model:
  conv_embeded: 
    feature: 80
    in_channels: 1         # feature dim
    out_channels: 192        # = output dim of conv_embeded & It's the input dim of encoder
    dropout_rate: 0.1
  encoder:
  decoder: 
    type: 'lstm'   
    embedding_size: 512
    hidden_size: 512
    output_size: 256 
    n_layers: 2
    dropout: 0.2
  joint: 
    input_size: 512
    hidden_size: 320
  # vocab_size: 4866
  dropout: 0.1
  name : 'zipformer'
  share_weight: False
  

training:
  epochs: 100
  batch_size: 10
  save_path: "workspace/Zipformer/saves_w2i"
  voice_path: "workspace/dataset/voices"
  train_path : "workspace/dataset/train_w2i.json"
  dev_path : "workspace/dataset/test_w2i.json"
  test_path : "workspace/dataset/test_w2i.json"
  vocab_path : "workspace/dataset/vocab_w2i.json"
  log_path: "workspace/Zipformer/logs"
  result: "workspace/Zipformer/result.txt"
  reload: False


optim:
  # type: sgd
  # lr: 0.0005
  # momentum: 0.9
  # weight_decay: 0
  # begin_to_adjust_lr: 60
  # nesterov: None
  # decay_rate: 0.5

  type: adam
  lr: 0.001
  weight_decay: 0.0001
  decay_rate: 0.5

scheduler:
  lr_initial: 0.001
  n_warmup_steps: 10000

rnnt_loss:
  blank: 4
  reduction: "mean" 